### ISSUE TITLE
WHy does it work with sending 5 bytes leaving out the header-byte that is written in the sensirion-documentation?

### ISSUE THREAD

**Issue by StefanL38** [Seeed-Studio/Seeed_SCD30#2]
Hello everybody,

I have tested the library and got my SCD30 working. Then I started to analyse the code of the library.

For example When sending the command Altitude Compensation

```
example Set Temperature Offset 
I2C-protocol        
ByteNo  1       2    3        4       5       6
               Cmd  Cmd   Altidude Altidude  CRC  
      Header   MSB  LSB      MSB     LSB
Start  0xC2    0x54 0x03     0x01    0xF4    0x33 Stop  
```

The Sensirion-documentation says you have to send **six** byte beginning with the header

see here https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9.5_CO2/Sensirion_CO2_Sensors_SCD30_Interface_Description.pdf

But the given code is sending just 5 bytes

```
#define SCD30_SET_TEMPERATURE_OFFSET            0x5403


void SCD30::setTemperatureOffset(uint16_t offset) {
    writeCommandWithArguments(SCD30_SET_TEMP_OFFSET, offset);
}

void SCD30::writeCommandWithArguments(uint16_t command, uint16_t arguments) {
    uint8_t checkSum, buf[5] = { 0 };

    buf[0] = command >> 8;
    buf[1] = command & 0xff;
    buf[2] = arguments >> 8;
    buf[3] = arguments & 0xff;
    checkSum = calculateCrc(&buf[2], 2);
    buf[4] = checkSum;

    writeBuffer(buf, 5);   //<<== just sending 5 bytes leaving out the header is sufficient??
}


void SCD30::writeBuffer(uint8_t* data, uint8_t len) {
    Wire.beginTransmission(devAddr);
    Wire.write(data, len);
    Wire.endTransmission();
}
```

    writeBuffer(buf, 5);   **//\<\<== just sending 5 bytes leaving out the header is sufficient??**  
 

best regards Stefan

**Comment by ackPeng** [comment]
@StefanL38  In fact, the header information is sent when Wire.endTransmission() or Wire.requestFrom() is called. So no header information is added here.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
